version: "3.9"

services:
  file_backend:
    image: file_backend:latest
    build:
      context: ${PWD}
      dockerfile: docker/Dockerfile
    command: /bin/bash -c \
      "echo '[+] Run backend' && \
      python main.py"
    volumes:
      - ${PWD}/app:/app
    env_file:
      - ${PWD}/.env
    depends_on:
      file_database:
        condition: service_healthy
    networks:
      - like_network
    ports:
      - ${PORT}:${PORT}
    restart: unless-stopped
