version: "3.9"

services:
  file:
    image: file:latest
    build:
      context: ${PWD}/file
      dockerfile: docker/Dockerfile
    command: /bin/bash -c \
      "echo '[+] Running File Backend' && \
      python main.py"
    volumes:
      - ${PWD}/file/app:/app
    env_file:
      - ${PWD}/.env
    depends_on:
      file_database:
        condition: service_healthy
    expose:
      - ${FILE_PORT}
    networks:
      - like_network
    restart: always
