version: "3.9"

services:
  file_database:
    image: postgres:15-bookworm
    volumes:
      - postgres_file_data_database:/var/lib/postgresql/data/
    env_file:
      - ${PWD}/file/.env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    expose:
      - ${DATABASE_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USERNAME}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - like_network

volumes:
  postgres_file_data_database:
