version: "3.9"

services:
  file_tests:
    image: file_tests:latest
    build:
      context: ${PWD}/file
      dockerfile: docker/Dockerfile
    command: /bin/bash -c \
      "echo '[+] Run tests' && \
      python -m pytest --capture=sys --cov=app --cov-report html tests"
    volumes:
      - ${PWD}/file/:/app
    env_file:
      - ${PWD}/file/.env
    environment:
      DATABASE_HOSTNAME: file_tests_database
    depends_on:
      file_tests_database:
        condition: service_healthy
